---
title: "Stochastic Processes Assignment 1-b"
author: "Matthew Yu     Student ID: 0553501"
date: "2017/9/25"
output: pdf_document
---


##3. Let's Make a Deal.

This problem is based on an old game show called *Let's Make a Deal*. The game show contestant is shown three doors. Behind one door is a valuable prize (say a Porsche), and behind the other two doors are mules. The contestant picks a door. The game show host then opens one of the other two doors, and always shows the contestant a mule. The contestant then has the option of switching doors or staying with his original pick. If you were the contestant, what would you do and why?\  

*R*: The event representing that contestant chooses the valuable prize in the first guess\
*A*: The event representing that contestant wins the valuable prize\  

### Strategy No.1: Choosing to switch
$$\begin{aligned}
P(A)=P(A\cap R)+P(A\cap R')&=P(A|R)P(R)+P(A|R')P(R')\\
&=0\times\frac{1}{3}+1\times\frac{2}{3}=\frac{2}{3}
\end{aligned}$$\  

### Strategy No.2: Choosing not to switch
$$\begin{aligned}
P(A)=P(A\cap R)+P(A\cap R')&=P(A|R)P(R)+P(A|R')P(R')\\
&=1\times\frac{1}{3}+0\times\frac{2}{3}=\frac{1}{3}
\end{aligned}$$\  

Therefore, choosing to switch is the better strategy\  

##4. Problem 1.23
For events $E_1,E_2,E_3,\dotso ,E_n$ show that $P(E_1E_2\dotso E_n)=P(E_1)P(E_2|E_1)P(E_3|E_1E_2)\cdots P(E_n|E_1\cdots E_{n-1})$\  

$$\begin{aligned}
P(E_1)P(E_2|E_1)P(E_3|E_1E_2)\cdots P(E_n|E_1\cdots E_{n-1})
&=P(E_1)\times \frac{P(E_1E_2)}{P(E_1)} \times \frac{P(E_1E_2E_3)}{P(E_1E_2)} \times \cdots \times \frac{P(E_1E_2\cdots E_n)}{P(E_1E_2 \cdots E_{n-1})}\\
&=P(E_1E_2 \cdots E_n)
\end{aligned}$$\  

##4. Problem 1.46
Three prisoners are informs by their jailer that one of them has been chosen at random to be executed, and the other two are to be freed. Prisoner A asks the jailer to tell him privately which of his fellow prisoners will be set free, claiming that there would be no harm in divulging this information, since he already knows that at least one will go free. The jailer refuses to answer this question, pointing out that if A knew which of his fellows were to be set free, then his own probability of being executed would rise from \(\frac{1}{3}\) to \(\frac{1}{2}\) , since he would then be one of two prisoners. What do you think of the jailer’s reasoning?\  

The jailer's reasoning makes no sense to me.\
Intuitively, the \(\frac{1}{2}\) derived by the jailer is the posterior probability given that *B will be freed*, instead of jailer telling A that B will be freed. Therefore the information doesn't have impact on the result.
